# templates/workflow_template.py

WORKFLOW_TEMPLATE = """\
# {title}

> Auto-generated from YouTube: https://www.youtube.com/watch?v={video_id}
> Generated: {date} | Language: {language} | Duration: {duration}
{auto_generated_warning}
## Summary

{summary}

## Prerequisites

{prerequisites}

## Tools & Commands Referenced

{tools}

## Step-by-Step Instructions

{steps}

## Warnings & Gotchas

{warnings}

## Tips & Optimizations

{tips}

---
*Auto-generated by youtube-to-workflow. Verify all steps before executing in production.*
"""


def render_prerequisites(items: list) -> str:
    if not items:
        return "_None specified_"
    return "\n".join(f"- [ ] {item}" for item in items)


def render_tools(items: list) -> str:
    if not items:
        return "_None specified_"
    return "\n".join(f"- `{item}`" for item in items)


def render_steps(steps: list) -> str:
    parts = []
    for step in steps:
        section = f"### Step {step['number']}: {step['title']}\n\n{step['description']}"
        if step.get("command"):
            section += f"\n\n```bash\n{step['command']}\n```"
        if step.get("expected_output"):
            section += f"\n\nExpected output:\n```\n{step['expected_output']}\n```"
        parts.append(section)
    return "\n\n".join(parts)


def render_warnings(items: list) -> str:
    if not items:
        return "_None_"
    return "\n".join(f"> \u26a0\ufe0f {item}" for item in items)


def render_tips(items: list) -> str:
    if not items:
        return "_None_"
    return "\n".join(f"- {item}" for item in items)
